package main

import (
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strings"
)

// This file turns the IR into Dart source. It never touches go/ast and only
// reads reflect.Type kinds, so the shape decisions all live upstream.
//
// Two properties matter more than elegance here:
//
//   - Determinism. The output is committed as a golden and diffed by cats's own
//     `make check`, so any map iteration must be sorted and nothing may carry a
//     timestamp or a version stamp.
//   - Total decoding. Every fromJson tolerates a missing or wrong-typed key and
//     falls back to the zero value, because a phone that throws on one
//     unexpected message loses the whole socket — and the server is free to add
//     fields within a protocol version (that is the point of §0.3 being
//     additive). Absent is not an error; it is the zero value.

type emitter struct {
	src *source
	reg *registry
	b   strings.Builder
}

func (e *emitter) p(format string, args ...any) {
	if len(args) == 0 {
		e.b.WriteString(format)
	} else {
		fmt.Fprintf(&e.b, format, args...)
	}
	e.b.WriteByte('\n')
}

func (e *emitter) nl() { e.b.WriteByte('\n') }

// doc re-emits a Go doc comment as Dart /// lines at the given indent. Blank
// lines are preserved as bare ///, which is how dartdoc separates paragraphs.
func (e *emitter) doc(indent, text string) {
	if text == "" {
		return
	}
	for line := range strings.SplitSeq(text, "\n") {
		line = strings.TrimRight(line, " \t")
		if line == "" {
			e.p("%s///", indent)
			continue
		}
		e.p("%s/// %s", indent, backtickAngles(line))
	}
}

// angleToken matches a placeholder like <id> or <pkgpath> written in Go prose.
var angleToken = regexp.MustCompile(`<[A-Za-z_][A-Za-z0-9_.:/-]*>`)

// backtickAngles quotes bare <angle> placeholders so dartdoc does not read them
// as HTML tags and silently swallow them. Segments already inside backticks are
// left alone — Go prose writes `<id>` both ways and double-quoting would show
// the backticks to the reader.
func backtickAngles(line string) string {
	parts := strings.Split(line, "`")
	for i := 0; i < len(parts); i += 2 { // even segments are outside backticks
		parts[i] = angleToken.ReplaceAllString(parts[i], "`$0`")
	}
	return strings.Join(parts, "`")
}

func (e *emitter) header(purpose string, sources []string) {
	e.p("// GENERATED BY cmd/catgen-dart — DO NOT EDIT.")
	e.p("//")
	e.p("// %s", purpose)
	e.p("//")
	e.p("// Source of truth (in the cats repo):")
	for _, s := range sources {
		e.p("//   %s", s)
	}
	e.p("//")
	e.p("// Regenerate:  go run ./cmd/catgen-dart -out <this directory>")
	e.p("//")
	e.p("// A stale copy fails cats's own `make check` — cmd/catgen-dart holds a")
	e.p("// committed golden and diffs it, so adding a field to a wire struct without")
	e.p("// regenerating breaks the GO build, not just this package's.")
	e.p("//")
	e.p("// No == / hashCode is generated. Deep value equality over the List and Map")
	e.p("// fields would need package:collection, and this package is deliberately")
	e.p("// zero-dependency; round-trip tests compare jsonEncode(toJson()) instead.")
	e.nl()
	// The formatter is switched off so this file and the golden committed in cats
	// are the SAME bytes. Otherwise there are two artefacts of one generation —
	// the raw output cats diffs and the formatted copy the app ships — and
	// cats-mobile's regenerate-and-git-diff gate could only ever compare the
	// second, which is one transformation away from what actually drifted.
	e.p("// dart format off")
	e.nl()
}

// --- type mapping ---------------------------------------------------------------

// dartType is the Dart type for a Go field type. ptr (a Go pointer) makes it
// nullable; json.RawMessage is already Object? and cannot be made "more" null.
func (e *emitter) dartType(t reflect.Type, ptr bool) string {
	base := e.dartBase(t)
	if ptr && base != "Object?" {
		return base + "?"
	}
	return base
}

func (e *emitter) dartBase(t reflect.Type) string {
	if ac := namedArray(t); ac != nil {
		return ac.dart
	}
	if t == rawMessageType {
		return "Object?"
	}
	if isByteSlice(t) {
		return "Uint8List"
	}
	switch t.Kind() {
	case reflect.String:
		return "String"
	case reflect.Bool:
		return "bool"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "int"
	case reflect.Float32, reflect.Float64:
		return "double"
	case reflect.Slice, reflect.Array:
		return "List<" + e.dartElem(t.Elem()) + ">"
	case reflect.Map:
		return "Map<String, " + e.dartElem(t.Elem()) + ">"
	case reflect.Struct:
		if c, ok := e.reg.byKey[typeKey(t)]; ok {
			return c.dart
		}
	}
	panic(fmt.Sprintf("catgen-dart: no Dart type for %s (kind %s)", t, t.Kind()))
}

// dartElem is dartBase for a collection element, which may itself be a pointer.
func (e *emitter) dartElem(t reflect.Type) string {
	if t.Kind() == reflect.Pointer {
		return e.dartBase(t.Elem()) + "?"
	}
	return e.dartBase(t)
}

// decode renders an expression producing the field's Dart value from src, an
// Object? expression. Every branch is total: a missing or wrong-typed value
// yields the zero, never a throw.
func (e *emitter) decode(t reflect.Type, ptr bool, src string) string {
	if ac := namedArray(t); ac != nil {
		if ptr {
			return fmt.Sprintf("%s == null ? null : %s.fromJson(%s)", src, ac.dart, src)
		}
		return fmt.Sprintf("%s.fromJson(%s)", ac.dart, src)
	}
	if t == rawMessageType {
		return src // already Object?; the caller decodes it against the command's result type
	}
	if isByteSlice(t) {
		if ptr {
			return fmt.Sprintf("%s == null ? null : asBytes(%s)", src, src)
		}
		return fmt.Sprintf("asBytes(%s)", src)
	}
	switch t.Kind() {
	case reflect.String:
		return e.scalar("asString", ptr, src)
	case reflect.Bool:
		return e.scalar("asBool", ptr, src)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return e.scalar("asInt", ptr, src)
	case reflect.Float32, reflect.Float64:
		return e.scalar("asDouble", ptr, src)
	case reflect.Slice, reflect.Array:
		return fmt.Sprintf("asList(%s, %s)", src, e.elemFn(t.Elem()))
	case reflect.Map:
		return fmt.Sprintf("asMap(%s, %s)", src, e.elemFn(t.Elem()))
	case reflect.Struct:
		name := e.dartBase(t)
		if ptr {
			return fmt.Sprintf("%s == null ? null : %s.fromJson(asObj(%s))", src, name, src)
		}
		return fmt.Sprintf("%s.fromJson(asObj(%s))", name, src)
	}
	panic(fmt.Sprintf("catgen-dart: no decoder for %s", t))
}

func (e *emitter) scalar(fn string, ptr bool, src string) string {
	if ptr {
		return fmt.Sprintf("%sOrNull(%s)", fn, src)
	}
	return fmt.Sprintf("%s(%s)", fn, src)
}

// elemFn is the Object?→T converter passed to asList/asMap. The scalar helpers
// already have that signature, so they are named directly rather than wrapped.
func (e *emitter) elemFn(t reflect.Type) string {
	ptr := false
	if t.Kind() == reflect.Pointer {
		t, ptr = t.Elem(), true
	}
	inner := e.decode(t, ptr, "e")
	switch inner {
	case "asString(e)", "asInt(e)", "asBool(e)", "asDouble(e)":
		return strings.TrimSuffix(inner, "(e)") // the helper is already (Object?) → T
	}
	return "(e) => " + inner
}

// encode renders src (already the Dart field) as the JSON value to write.
func (e *emitter) encode(t reflect.Type, ptr bool, src string) string {
	if ac := namedArray(t); ac != nil {
		if ptr {
			return src + "?.toJson()"
		}
		return src + ".toJson()"
	}
	if t == rawMessageType {
		return src
	}
	if isByteSlice(t) {
		if ptr {
			return fmt.Sprintf("%s == null ? null : base64Encode(%s)", src, src)
		}
		return fmt.Sprintf("base64Encode(%s)", src)
	}
	switch t.Kind() {
	case reflect.Struct:
		if ptr {
			return src + "?.toJson()"
		}
		return src + ".toJson()"
	case reflect.Slice, reflect.Array:
		if inner := e.encodeElem(t.Elem(), "e"); inner != "e" {
			return fmt.Sprintf("[for (final e in %s) %s]", src, inner)
		}
		return src
	case reflect.Map:
		if inner := e.encodeElem(t.Elem(), "e.value"); inner != "e.value" {
			return fmt.Sprintf("{for (final e in %s.entries) e.key: %s}", src, inner)
		}
		return src
	}
	return src // scalars pass straight through
}

func (e *emitter) encodeElem(t reflect.Type, src string) string {
	ptr := false
	if t.Kind() == reflect.Pointer {
		t, ptr = t.Elem(), true
	}
	return e.encode(t, ptr, src)
}

// zeroLit is the Dart default for an omitempty field: the value that makes
// toJson leave the key out, which is exactly Go's zero.
func (e *emitter) zeroLit(t reflect.Type, ptr bool) string {
	if ptr || t == rawMessageType {
		return "null"
	}
	if isByteSlice(t) {
		return "null" // see emitField: an omitempty []byte becomes nullable
	}
	if namedArray(t) != nil {
		return "" // no const empty; such a field must be required
	}
	switch t.Kind() {
	case reflect.String:
		return "''"
	case reflect.Bool:
		return "false"
	case reflect.Float32, reflect.Float64:
		return "0"
	case reflect.Slice, reflect.Array:
		return "const <" + e.dartElem(t.Elem()) + ">[]"
	case reflect.Map:
		return "const <String, " + e.dartElem(t.Elem()) + ">{}"
	case reflect.Struct:
		return ""
	}
	return "0"
}

// present renders the omitempty guard: the Dart condition under which the key
// is written at all.
func (e *emitter) present(t reflect.Type, ptr bool, src string) string {
	if ptr || t == rawMessageType || isByteSlice(t) {
		return src + " != null"
	}
	switch t.Kind() {
	case reflect.String:
		return src + ".isNotEmpty"
	case reflect.Bool:
		return src
	case reflect.Slice, reflect.Array, reflect.Map:
		return src + ".isNotEmpty"
	}
	return src + " != 0"
}

// --- class emission ---------------------------------------------------------------

func (e *emitter) class(c *classDef) {
	e.doc("", c.doc)
	if c.disc != "" {
		if c.doc != "" {
			e.p("///")
		}
		e.p("/// Wire type: `%s`.", c.disc)
	}
	if c.deprecated != "" {
		e.p("@Deprecated(%s)", dartString(c.deprecated))
	}
	e.p("class %s {", c.dart)

	// Constructor.
	if len(c.fields) == 0 {
		e.p("  const %s();", c.dart)
	} else {
		e.p("  const %s({", c.dart)
		for _, f := range c.fields {
			nullable := f.ptr || f.rt == rawMessageType || (f.omitempty && isByteSlice(f.rt))
			zero := e.zeroLit(f.rt, f.ptr)
			switch {
			case nullable:
				e.p("    this.%s,", f.dart)
			case f.omitempty && zero != "":
				e.p("    this.%s = %s,", f.dart, zero)
			default:
				e.p("    required this.%s,", f.dart)
			}
		}
		e.p("  });")
	}
	e.nl()

	if c.disc != "" {
		e.p("  /// The `t` discriminator this class always carries. It is a property of")
		e.p("  /// the type, not a field: a caller who could set it could set it wrong.")
		e.p("  static const String type = %s;", dartString(c.disc))
		e.nl()
	}

	// Fields. A blank line separates only DOCUMENTED members: a run of bare
	// finals reads as the record it is, and double-spacing it would bury the
	// fields that actually have something to say.
	for i, f := range c.fields {
		if i > 0 && f.doc != "" {
			e.nl()
		}
		e.doc("  ", f.doc)
		nullable := f.ptr || (f.omitempty && isByteSlice(f.rt))
		e.p("  final %s %s;", e.dartType(f.rt, nullable), f.dart)
	}
	if len(c.fields) > 0 {
		e.nl()
	}

	// Embedded-struct regrouping.
	for _, em := range c.embeds {
		e.p("  /// The embedded `%s` block, regrouped. Go's embedding flattens these", em.dart)
		e.p("  /// onto the wire; this hands them back as the unit they were declared as.")
		e.p("  %s get %s => %s(", em.dart, em.getter, em.dart)
		for _, f := range em.fields {
			e.p("        %s: %s,", f.dart, f.dart)
		}
		e.p("      );")
		e.nl()
	}

	// fromJson.
	if len(c.fields) == 0 {
		e.p("  factory %s.fromJson(Map<String, Object?> j) => const %s();", c.dart, c.dart)
	} else {
		e.p("  factory %s.fromJson(Map<String, Object?> j) => %s(", c.dart, c.dart)
		for _, f := range c.fields {
			e.p("        %s: %s,", f.dart, e.decode(f.rt, f.ptr, fmt.Sprintf("j[%s]", dartString(f.json))))
		}
		e.p("      );")
	}
	e.nl()

	// toJson.
	e.p("  Map<String, Object?> toJson() => {")
	if c.disc != "" {
		e.p("        't': type,")
	}
	for _, f := range c.fields {
		key := dartString(f.json)
		nullable := f.ptr || (f.omitempty && isByteSlice(f.rt))
		val := e.encode(f.rt, nullable, f.dart)
		if f.omitempty {
			e.p("        if (%s) %s: %s,", e.present(f.rt, nullable, f.dart), key, val)
		} else {
			e.p("        %s: %s,", key, val)
		}
	}
	e.p("      };")
	e.p("}")
	e.nl()
}

// arrayClassSrc emits the hand-shaped classes that stand in for fixed-size Go
// arrays. They serialize BACK to the array, so the wire is untouched.
func (e *emitter) arrayClass(ac *arrayClass) {
	e.doc("", ac.doc)
	e.p("class %s {", ac.dart)
	e.p("  const %s(%s);", ac.dart, joinPrefixed(ac.components, "this."))
	e.nl()
	for _, comp := range ac.components {
		e.p("  final int %s;", comp)
	}
	e.nl()
	e.p("  /// Total: a short, long or absent array yields zeros rather than throwing.")
	e.p("  factory %s.fromJson(Object? v) {", ac.dart)
	e.p("    final a = v is List ? v : const <Object?>[];")
	e.p("    int at(int i) => i < a.length && a[i] is num ? (a[i] as num).toInt() : 0;")
	args := make([]string, len(ac.components))
	for i := range ac.components {
		args[i] = fmt.Sprintf("at(%d)", i)
	}
	e.p("    return %s(%s);", ac.dart, strings.Join(args, ", "))
	e.p("  }")
	e.nl()
	e.p("  List<int> toJson() => [%s];", strings.Join(ac.components, ", "))
	e.nl()
	e.p("  @override")
	e.p("  bool operator ==(Object other) =>")
	conds := make([]string, len(ac.components))
	for i, comp := range ac.components {
		conds[i] = fmt.Sprintf("%s == other.%s", comp, comp)
	}
	e.p("      other is %s &&", ac.dart)
	for i, cond := range conds {
		tail := " &&"
		if i == len(conds)-1 {
			tail = ";"
		}
		e.p("      %s%s", cond, tail)
	}
	e.nl()
	e.p("  @override")
	e.p("  int get hashCode => Object.hash(%s);", strings.Join(ac.components, ", "))
	e.nl()
	e.p("  @override")
	e.p("  String toString() => '%s(%s)';", ac.dart, joinInterp(ac.components))
	e.p("}")
	e.nl()
}

// --- constant groups -----------------------------------------------------------

// constGroup emits one Go const block as a Dart holder class. The VALUES come
// from go/ast; only the naming lives in the table, so a changed wire string
// cannot silently keep its old Dart spelling.
type constGroup struct {
	class  string // Dart holder class name
	doc    string
	typ    string // "String" | "int" | "double"
	pkg    string // Go package path
	first  string // the const block's first member — its key in source.groups
	strip  string // prefix removed from each Go name to make the Dart one
	filter func(string) bool
}

func (e *emitter) constGroup(g constGroup) error {
	names := e.src.groups[g.pkg+"."+g.first]
	if len(names) == 0 {
		return fmt.Errorf("const group %s.%s not found", g.pkg, g.first)
	}
	e.doc("", g.doc)
	e.p("abstract final class %s {", g.class)
	first := true
	for _, name := range names {
		if g.filter != nil && !g.filter(name) {
			continue
		}
		c := e.src.consts[g.pkg+"."+name]
		if c == nil {
			return fmt.Errorf("const %s.%s did not resolve to a literal", g.pkg, name)
		}
		if !first && c.doc != "" {
			e.nl()
		}
		first = false
		e.doc("  ", c.doc)
		member := lowerFirst(strings.TrimPrefix(name, g.strip))
		line := fmt.Sprintf("  static const %s %s = %s;", g.typ, member, c.dart)
		// Dart has no binary literals; keep the Go bit pattern visible beside the
		// hex, because "bit 6" is the thing being asserted, not the number 0x40.
		if strings.HasPrefix(c.goSource, "0b") {
			line += " // " + c.goSource
		}
		e.p("%s", line)
	}
	e.p("}")
	e.nl()
	return nil
}

// topConst emits a single Go const as a Dart top-level.
func (e *emitter) topConst(pkg, name, dartName, typ, extraDoc string) error {
	c := e.src.consts[pkg+"."+name]
	if c == nil {
		return fmt.Errorf("const %s.%s not found", pkg, name)
	}
	e.doc("", c.doc)
	if extraDoc != "" {
		if c.doc != "" {
			e.p("///")
		}
		e.doc("", extraDoc)
	}
	e.p("const %s %s = %s;", typ, dartName, c.dart)
	e.nl()
	return nil
}

// --- small helpers ---------------------------------------------------------------

// dartString renders a Go string as a single-quoted Dart literal. Dart
// interpolates $ inside any string literal, so it must be escaped alongside the
// quote and backslash.
func dartString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`, `$`, `\$`, "\n", `\n`, "\r", `\r`)
	return "'" + r.Replace(s) + "'"
}

func joinPrefixed(items []string, prefix string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = prefix + s
	}
	return strings.Join(out, ", ")
}

func joinInterp(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "$" + s
	}
	return strings.Join(out, ", ")
}

func sortedClasses(classes []*classDef) []*classDef {
	out := append([]*classDef(nil), classes...)
	sort.Slice(out, func(i, j int) bool { return out[i].dart < out[j].dart })
	return out
}
