// Code generated by aliasgen from ../../wire/vocab.go; DO NOT EDIT by hand.
//
// The §7 command vocabulary moved to package wire so that an out-of-tree
// client can import it without the server. Everything below is an alias, not
// a copy: app.SplitParams and wire.SplitParams are the same type, so the
// dispatcher, catway, catctl and the generator keep compiling unchanged.
// The four helpers that need internal/layout or internal/flags stayed here,
// in wire_convert.go. New code should import wire directly.

package app

import "github.com/rohanthewiz/cats/wire"

// Types.
type (
	CaptureParams            = wire.CaptureParams
	CaptureResult            = wire.CaptureResult
	ChatPermissionParams     = wire.ChatPermissionParams
	ChatSendParams           = wire.ChatSendParams
	CommandSpec              = wire.CommandSpec
	ConfigGetResult          = wire.ConfigGetResult
	ConfigServerInfo         = wire.ConfigServerInfo
	ConfigSetParams          = wire.ConfigSetParams
	ConfigTheme              = wire.ConfigTheme
	CycleParams              = wire.CycleParams
	DirParams                = wire.DirParams
	EditorInfo               = wire.EditorInfo
	FileGetParams            = wire.FileGetParams
	FileGetResult            = wire.FileGetResult
	FilePutParams            = wire.FilePutParams
	FilePutResult            = wire.FilePutResult
	FileStatParams           = wire.FileStatParams
	FileStatResult           = wire.FileStatResult
	FlagInfo                 = wire.FlagInfo
	FlagListParams           = wire.FlagListParams
	FlagListResult           = wire.FlagListResult
	FlagPaneParams           = wire.FlagPaneParams
	FlagWorkspaceParams      = wire.FlagWorkspaceParams
	HostAttachParams         = wire.HostAttachParams
	HostDetachParams         = wire.HostDetachParams
	HostInfo                 = wire.HostInfo
	HostListResult           = wire.HostListResult
	LedgerBlockParams        = wire.LedgerBlockParams
	LedgerEntry              = wire.LedgerEntry
	LedgerListParams         = wire.LedgerListParams
	LedgerListResult         = wire.LedgerListResult
	LedgerOutputResult       = wire.LedgerOutputResult
	LockWorkspaceParams      = wire.LockWorkspaceParams
	CleanWorkspaceParams     = wire.CleanWorkspaceParams
	CleanWorkspaceResult     = wire.CleanWorkspaceResult
	ParkedAgentInfo          = wire.ParkedAgentInfo
	MoveTabParams            = wire.MoveTabParams
	MoveTabToWorkspaceParams = wire.MoveTabToWorkspaceParams
	MoveTabToWorkspaceResult = wire.MoveTabToWorkspaceResult
	MoveWorkspaceParams      = wire.MoveWorkspaceParams
	NotifyAction             = wire.NotifyAction
	OpenFileParams           = wire.OpenFileParams
	OpenFileResult           = wire.OpenFileResult
	OptPaneParams            = wire.OptPaneParams
	OptTabParams             = wire.OptTabParams
	PaneInfo                 = wire.PaneInfo
	PaneListResult           = wire.PaneListResult
	PaneMeta                 = wire.PaneMeta
	PaneParams               = wire.PaneParams
	PathListParams           = wire.PathListParams
	PathListResult           = wire.PathListResult
	PluginActionInfo         = wire.PluginActionInfo
	PluginInfo               = wire.PluginInfo
	PluginListResult         = wire.PluginListResult
	PluginUninstallParams    = wire.PluginUninstallParams
	PluginUninstallResult    = wire.PluginUninstallResult
	ReadParams               = wire.ReadParams
	ReadResult               = wire.ReadResult
	RenamePaneParams         = wire.RenamePaneParams
	RenameTabParams          = wire.RenameTabParams
	RenameWorkspaceParams    = wire.RenameWorkspaceParams
	ResizeBorderParams       = wire.ResizeBorderParams
	RunbookInfo              = wire.RunbookInfo
	RunbookListResult        = wire.RunbookListResult
	RunbookRecordParams      = wire.RunbookRecordParams
	RunbookRecordResult      = wire.RunbookRecordResult
	RunbookRunParams         = wire.RunbookRunParams
	RunbookRunResult         = wire.RunbookRunResult
	RunbookStepResult        = wire.RunbookStepResult
	ScrollParams             = wire.ScrollParams
	SendInputParams          = wire.SendInputParams
	SessionInfoResult        = wire.SessionInfoResult
	SpawnOverride            = wire.SpawnOverride
	SplitParams              = wire.SplitParams
	SplitResult              = wire.SplitResult
	SwapWithParams           = wire.SwapWithParams
	TabCreateParams          = wire.TabCreateParams
	TabCreateResult          = wire.TabCreateResult
	TabEntry                 = wire.TabEntry
	TabListParams            = wire.TabListParams
	TabListResult            = wire.TabListResult
	TabParams                = wire.TabParams
	ThemeDeleteParams        = wire.ThemeDeleteParams
	ThemeInfo                = wire.ThemeInfo
	ThemeListResult          = wire.ThemeListResult
	ThemeSaveParams          = wire.ThemeSaveParams
	UIActionParams           = wire.UIActionParams
	UINotifyParams           = wire.UINotifyParams
	UINotifyResult           = wire.UINotifyResult
	WaitForOutputParams      = wire.WaitForOutputParams
	WaitForOutputResult      = wire.WaitForOutputResult
	WorkspaceCreateParams    = wire.WorkspaceCreateParams
	WorkspaceCreateResult    = wire.WorkspaceCreateResult
	WorkspaceEntry           = wire.WorkspaceEntry
	WorkspaceListResult      = wire.WorkspaceListResult
	WorkspaceParams          = wire.WorkspaceParams
	WorktreeCreateParams     = wire.WorktreeCreateParams
	WorktreeCreateResult     = wire.WorktreeCreateResult
	WorktreeInfo             = wire.WorktreeInfo
	WorktreeListParams       = wire.WorktreeListParams
	WorktreeListResult       = wire.WorktreeListResult
	WorktreeOpenParams       = wire.WorktreeOpenParams
	WorktreeOpenResult       = wire.WorktreeOpenResult
	WorktreeRemoveParams     = wire.WorktreeRemoveParams
)

// Constants.
const (
	CmdAgentFocus         = wire.CmdAgentFocus
	CmdCapture            = wire.CmdCapture
	CmdChatCancel         = wire.CmdChatCancel
	CmdChatClear          = wire.CmdChatClear
	CmdChatPermission     = wire.CmdChatPermission
	CmdChatSend           = wire.CmdChatSend
	CmdConfigGet          = wire.CmdConfigGet
	CmdConfigSet          = wire.CmdConfigSet
	CmdFileGet            = wire.CmdFileGet
	CmdFilePut            = wire.CmdFilePut
	CmdFileStat           = wire.CmdFileStat
	CmdFlagList           = wire.CmdFlagList
	CmdHostAttach         = wire.CmdHostAttach
	CmdHostDetach         = wire.CmdHostDetach
	CmdHostList           = wire.CmdHostList
	CmdLedgerJump         = wire.CmdLedgerJump
	CmdLedgerList         = wire.CmdLedgerList
	CmdLedgerOutput       = wire.CmdLedgerOutput
	CmdNavBack            = wire.CmdNavBack
	CmdNavForward         = wire.CmdNavForward
	CmdPaneClose          = wire.CmdPaneClose
	CmdPaneKeep           = wire.CmdPaneKeep
	CmdPaneCycle          = wire.CmdPaneCycle
	CmdPaneFlag           = wire.CmdPaneFlag
	CmdPaneFocus          = wire.CmdPaneFocus
	CmdPaneFocusDirection = wire.CmdPaneFocusDirection
	CmdPaneGet            = wire.CmdPaneGet
	CmdPaneLast           = wire.CmdPaneLast
	CmdPaneList           = wire.CmdPaneList
	CmdPaneOpenFile       = wire.CmdPaneOpenFile
	CmdPaneRename         = wire.CmdPaneRename
	CmdPaneResizeBorder   = wire.CmdPaneResizeBorder
	CmdPaneSendInput      = wire.CmdPaneSendInput
	CmdPaneSplit          = wire.CmdPaneSplit
	CmdPaneSwap           = wire.CmdPaneSwap
	CmdPaneSwapWith       = wire.CmdPaneSwapWith
	CmdPaneZoom           = wire.CmdPaneZoom
	CmdPathList           = wire.CmdPathList
	CmdPluginList         = wire.CmdPluginList
	CmdPluginUninstall    = wire.CmdPluginUninstall
	CmdRead               = wire.CmdRead
	CmdRunbookList        = wire.CmdRunbookList
	CmdRunbookRecord      = wire.CmdRunbookRecord
	CmdRunbookRun         = wire.CmdRunbookRun
	CmdScroll             = wire.CmdScroll
	CmdServerReloadConfig = wire.CmdServerReloadConfig
	CmdServerStop         = wire.CmdServerStop
	CmdSessionGet         = wire.CmdSessionGet
	CmdTabClose           = wire.CmdTabClose
	CmdTabCreate          = wire.CmdTabCreate
	CmdTabFocus           = wire.CmdTabFocus
	CmdTabList            = wire.CmdTabList
	CmdTabMove            = wire.CmdTabMove
	CmdTabMoveToWorkspace = wire.CmdTabMoveToWorkspace
	CmdTabRename          = wire.CmdTabRename
	CmdThemeDelete        = wire.CmdThemeDelete
	CmdThemeList          = wire.CmdThemeList
	CmdThemeSave          = wire.CmdThemeSave
	CmdUIAction           = wire.CmdUIAction
	CmdUINotify           = wire.CmdUINotify
	CmdUsageRefresh       = wire.CmdUsageRefresh
	CmdWaitForOutput      = wire.CmdWaitForOutput
	CmdWorkspaceClose     = wire.CmdWorkspaceClose
	CmdWorkspaceCreate    = wire.CmdWorkspaceCreate
	CmdWorkspaceFlag      = wire.CmdWorkspaceFlag
	CmdWorkspaceFocus     = wire.CmdWorkspaceFocus
	CmdWorkspaceList      = wire.CmdWorkspaceList
	CmdWorkspaceLock      = wire.CmdWorkspaceLock
	CmdWorkspaceClean     = wire.CmdWorkspaceClean
	CmdWorkspaceSleep     = wire.CmdWorkspaceSleep
	CmdWorkspaceWake      = wire.CmdWorkspaceWake
	CmdWorkspaceMove      = wire.CmdWorkspaceMove
	CmdWorkspaceRename    = wire.CmdWorkspaceRename
	CmdWorktreeCreate     = wire.CmdWorktreeCreate
	CmdWorktreeList       = wire.CmdWorktreeList
	CmdWorktreeOpen       = wire.CmdWorktreeOpen
	CmdWorktreeRemove     = wire.CmdWorktreeRemove
	DirDown               = wire.DirDown
	DirLeft               = wire.DirLeft
	DirRight              = wire.DirRight
	DirUp                 = wire.DirUp
	MaxRunbookRuntime     = wire.MaxRunbookRuntime
	MaxWaitTimeout        = wire.MaxWaitTimeout
	NotifyKindAttention   = wire.NotifyKindAttention
	NotifyKindFinished    = wire.NotifyKindFinished
	NotifyKindInfo        = wire.NotifyKindInfo
	RecordCancel          = wire.RecordCancel
	RecordStart           = wire.RecordStart
	RecordStatus          = wire.RecordStatus
	RecordStop            = wire.RecordStop
	SplitH                = wire.SplitH
	SplitV                = wire.SplitV
)

// Functions, as values: callers use them exactly as before.
var (
	BorderPath      = wire.BorderPath
	CommandNames    = wire.CommandNames
	CommandSpecs    = wire.CommandSpecs
	NotifyKindOK    = wire.NotifyKindOK
	UniqueActionIDs = wire.UniqueActionIDs
	WaitTimeout     = wire.WaitTimeout
)
