//go:build ghostty

package inputenc

import (
	"testing"

	libghostty "go.mitchellh.com/libghostty"
)

// This is the far end of the chain every structured key event takes:
//
//	KeyboardEvent.code                   (a browser reports this verbatim —
//	                                      cmd/catway/web/js/20-keys.js)
//	  → wire.Key{Code: "KeyA"}           (the wire)
//	    → w3cKeyName → ParseKey          (this file's subject)
//	      → VT bytes                     (encoder.go)
//
// The chain used to have a second head: the Flutter phone reported
// PhysicalKeyboardKey.usbHidUsage and a table generated by cmd/catgen-dart
// (kUsbHidToW3cCode, committed as keys.g.dart) turned it into a W3C code. That
// head is gone with 5add396 — cats-mobile is Go on grmob, imports wire
// directly, and sends no wire.Key at all (its composer types text through
// pane.send_input). No USB HID → W3C table exists in Go anywhere, so the
// USB-usage half of the old checks had nothing left to guard and was dropped.
//
// The half that survives is the one that tests live code: w3cKeyName feeding
// libghostty.ParseKey. The browser forwards e.code without filtering, so any
// code a keyboard can produce reaches that conversion. A code that reaches
// ghostty and does not parse is not an error anyone sees — encoder.go falls
// back to KeyUnidentified — it is a key that silently does nothing, which is
// the worst failure mode a keyboard can have.

// knownW3CCodes is the universe of KeyboardEvent.code values the conversion is
// checked against: 269 names, the DOM code table Chromium defines and Flutter's
// physical_key_data.g.json transcribes (entry.names.name), as last generated
// into keys.g.dart before that file was deleted.
//
// It is a frozen fixture rather than something read from disk because its
// only generator needed a Flutter SDK checkout and no longer exists; the codes
// themselves change only when the UI Events spec or Chromium adds keys, which
// is rare. Sorted (C collation) so a diff against a new list is readable.
//
// It is a superset of what a desktop browser emits in practice (gamepad
// buttons and USB error sentinels among it). That is fine for this test's
// purpose: the partition below is exact, so an over-wide universe costs
// nothing and a missing code would be a silent hole.
var knownW3CCodes = []string{
	"Abort", "Again", "AltLeft", "AltRight", "ArrowDown", "ArrowLeft", "ArrowRight",
	"ArrowUp", "AudioVolumeDown", "AudioVolumeMute", "AudioVolumeUp", "Backquote",
	"Backslash", "Backspace", "BassBoost", "BracketLeft", "BracketRight",
	"BrightnessAuto", "BrightnessDown", "BrightnessMaximum", "BrightnessMinimum",
	"BrightnessToggle", "BrightnessUp", "BrowserBack", "BrowserFavorites",
	"BrowserForward", "BrowserHome", "BrowserRefresh", "BrowserSearch", "BrowserStop",
	"CapsLock", "ChannelDown", "ChannelUp", "Close", "ClosedCaptionToggle", "Comma",
	"ContextMenu", "ControlLeft", "ControlRight", "Convert", "Copy", "Cut", "Delete",
	"Digit0", "Digit1", "Digit2", "Digit3", "Digit4", "Digit5", "Digit6", "Digit7",
	"Digit8", "Digit9", "DisplayToggleIntExt", "Eject", "End", "Enter", "Equal",
	"Escape", "Exit", "F1", "F10", "F11", "F12", "F13", "F14", "F15", "F16", "F17",
	"F18", "F19", "F2", "F20", "F21", "F22", "F23", "F24", "F3", "F4", "F5", "F6", "F7",
	"F8", "F9", "Find", "Fn", "FnLock", "GameButton1", "GameButton10", "GameButton11",
	"GameButton12", "GameButton13", "GameButton14", "GameButton15", "GameButton16",
	"GameButton2", "GameButton3", "GameButton4", "GameButton5", "GameButton6",
	"GameButton7", "GameButton8", "GameButton9", "GameButtonA", "GameButtonB",
	"GameButtonC", "GameButtonLeft1", "GameButtonLeft2", "GameButtonMode",
	"GameButtonRight1", "GameButtonRight2", "GameButtonSelect", "GameButtonStart",
	"GameButtonThumbLeft", "GameButtonThumbRight", "GameButtonX", "GameButtonY",
	"GameButtonZ", "Help", "Home", "Hyper", "Info", "Insert", "IntlBackslash", "IntlRo",
	"IntlYen", "KanaMode", "KbdIllumDown", "KbdIllumUp", "KeyA", "KeyB", "KeyC", "KeyD",
	"KeyE", "KeyF", "KeyG", "KeyH", "KeyI", "KeyJ", "KeyK", "KeyL", "KeyM", "KeyN",
	"KeyO", "KeyP", "KeyQ", "KeyR", "KeyS", "KeyT", "KeyU", "KeyV", "KeyW", "KeyX",
	"KeyY", "KeyZ", "KeyboardLayoutSelect", "Lang1", "Lang2", "Lang3", "Lang4", "Lang5",
	"LaunchApp1", "LaunchApp2", "LaunchAssistant", "LaunchAudioBrowser",
	"LaunchCalendar", "LaunchContacts", "LaunchControlPanel", "LaunchDocuments",
	"LaunchInternetBrowser", "LaunchKeyboardLayout", "LaunchMail", "LaunchPhone",
	"LaunchScreenSaver", "LaunchSpreadsheet", "LaunchWordProcessor", "LockScreen",
	"LogOff", "MailForward", "MailReply", "MailSend", "MediaFastForward", "MediaLast",
	"MediaPause", "MediaPlay", "MediaPlayPause", "MediaRecord", "MediaRewind",
	"MediaSelect", "MediaStop", "MediaTrackNext", "MediaTrackPrevious", "MetaLeft",
	"MetaRight", "MicrophoneMuteToggle", "Minus", "New", "NonConvert", "NumLock",
	"Numpad0", "Numpad1", "Numpad2", "Numpad3", "Numpad4", "Numpad5", "Numpad6",
	"Numpad7", "Numpad8", "Numpad9", "NumpadAdd", "NumpadBackspace", "NumpadClear",
	"NumpadClearEntry", "NumpadComma", "NumpadDecimal", "NumpadDivide", "NumpadEnter",
	"NumpadEqual", "NumpadMemoryAdd", "NumpadMemoryClear", "NumpadMemoryRecall",
	"NumpadMemoryStore", "NumpadMemorySubtract", "NumpadMultiply", "NumpadParenLeft",
	"NumpadParenRight", "NumpadSignChange", "NumpadSubtract", "Open", "PageDown",
	"PageUp", "Paste", "Pause", "Period", "Power", "Print", "PrintScreen",
	"PrivacyScreenToggle", "ProgramGuide", "Props", "Quote", "Redo", "Resume", "Save",
	"ScrollLock", "Select", "SelectTask", "Semicolon", "ShiftLeft", "ShiftRight",
	"ShowAllWindows", "Slash", "Sleep", "Space", "SpeechInputToggle", "SpellCheck",
	"Super", "Suspend", "Tab", "Turbo", "Undo", "UsbErrorRollOver", "UsbErrorUndefined",
	"UsbPostFail", "UsbReserved", "WakeUp", "ZoomIn", "ZoomOut", "ZoomToggle",
}

// ghosttyUnknownCodes are the W3C codes ghostty does not model — 107 of the
// 269 above, leaving 162 that reach the encoder.
//
// The code universe is much larger than "keys a terminal can encode": gamepad
// buttons, the USB error sentinels, hardware launch keys, brightness and media
// transport, and the IME language keys. Nothing filters them before catway,
// deliberately — a client should report honestly which key was pressed, and
// catway's KeyUnidentified fallback is the correct answer for a key with no VT
// sequence.
//
// Recording the partition here rather than skipping it is what gives the test
// teeth in both directions. A code that stops parsing is a regression in
// w3cKeyName. A code that starts parsing means ghostty grew support and this
// list should shrink. Either way the build says so.
//
// Regenerate by listing every knownW3CCodes entry whose ParseKey fails, sorted.
var ghosttyUnknownCodes = []string{
	"Abort", "Again", "BassBoost", "BrightnessAuto", "BrightnessDown", "BrightnessMaximum",
	"BrightnessMinimum", "BrightnessToggle", "BrightnessUp", "ChannelDown", "ChannelUp",
	"Close", "ClosedCaptionToggle", "DisplayToggleIntExt", "Exit", "Find", "GameButton1",
	"GameButton10", "GameButton11", "GameButton12", "GameButton13", "GameButton14",
	"GameButton15", "GameButton16", "GameButton2", "GameButton3", "GameButton4",
	"GameButton5", "GameButton6", "GameButton7", "GameButton8", "GameButton9", "GameButtonA",
	"GameButtonB", "GameButtonC", "GameButtonLeft1", "GameButtonLeft2", "GameButtonMode",
	"GameButtonRight1", "GameButtonRight2", "GameButtonSelect", "GameButtonStart",
	"GameButtonThumbLeft", "GameButtonThumbRight", "GameButtonX", "GameButtonY",
	"GameButtonZ", "Hyper", "Info", "KbdIllumDown", "KbdIllumUp", "KeyboardLayoutSelect",
	"Lang1", "Lang2", "Lang3", "Lang4", "Lang5", "LaunchAssistant", "LaunchAudioBrowser",
	"LaunchCalendar", "LaunchContacts", "LaunchControlPanel", "LaunchDocuments",
	"LaunchInternetBrowser", "LaunchKeyboardLayout", "LaunchPhone", "LaunchScreenSaver",
	"LaunchSpreadsheet", "LaunchWordProcessor", "LockScreen", "LogOff", "MailForward",
	"MailReply", "MailSend", "MediaFastForward", "MediaLast", "MediaPause", "MediaPlay",
	"MediaRecord", "MediaRewind", "MicrophoneMuteToggle", "New", "NumpadSignChange", "Open",
	"Print", "PrivacyScreenToggle", "ProgramGuide", "Props", "Redo", "Resume", "Save",
	"Select", "SelectTask", "ShowAllWindows", "SpeechInputToggle", "SpellCheck", "Super",
	"Suspend", "Turbo", "Undo", "UsbErrorRollOver", "UsbErrorUndefined", "UsbPostFail",
	"UsbReserved", "ZoomIn", "ZoomOut", "ZoomToggle",
}

func TestW3CCodesReachGhostty(t *testing.T) {
	// Guard the fixture itself: a truncated or duplicated list would let the
	// partition pass by checking less than it claims to.
	seen := make(map[string]bool, len(knownW3CCodes))
	for _, code := range knownW3CCodes {
		if seen[code] {
			t.Errorf("%q appears twice in knownW3CCodes", code)
		}
		seen[code] = true
	}
	if len(knownW3CCodes) < 200 {
		t.Fatalf("knownW3CCodes has only %d entries; the fixture was truncated",
			len(knownW3CCodes))
	}

	expectedUnknown := make(map[string]bool, len(ghosttyUnknownCodes))
	for _, code := range ghosttyUnknownCodes {
		if !seen[code] {
			// An unknown code outside the universe would never be exercised, so
			// the "now parses" check below could not fire for it.
			t.Errorf("%q is in ghosttyUnknownCodes but not in knownW3CCodes", code)
		}
		expectedUnknown[code] = true
	}

	unparsed := map[string]bool{}
	reached := 0
	for _, code := range knownW3CCodes {
		if _, err := libghostty.ParseKey(w3cKeyName(code)); err != nil {
			unparsed[code] = true
			continue
		}
		reached++
	}

	// Both directions are failures, for different reasons.
	for code := range unparsed {
		if !expectedUnknown[code] {
			t.Errorf("%q → w3cKeyName %q no longer reaches ghostty. A client pressing "+
				"this key would silently do nothing — encoder.go falls back to "+
				"KeyUnidentified rather than erroring.", code, w3cKeyName(code))
		}
	}
	for _, code := range ghosttyUnknownCodes {
		if !unparsed[code] {
			t.Errorf("%q is listed in ghosttyUnknownCodes but now parses — "+
				"ghostty grew support for it; drop it from the list", code)
		}
	}
	t.Logf("%d of %d W3C codes reach libghostty.ParseKey", reached, len(knownW3CCodes))
}

// TestCommonKeysSurviveTheChain spot-checks the keys a client actually sends,
// naming them explicitly so the test does not depend on knownW3CCodes being
// complete — a fixture edited down to nothing cannot pass by having nothing to
// check.
//
// The old version also pinned each key's USB HID usage (0x7xxxx) to its code;
// that half guarded the generated Dart table and went with it. Home and End
// are here because 20-keys.js synthesizes them (⌘←/⌘→) rather than forwarding
// e.code, so they reach the encoder even from a keyboard without those keys.
func TestCommonKeysSurviveTheChain(t *testing.T) {
	common := []string{
		"KeyA", "KeyZ", "Digit1", "Enter", "Escape", "Backspace", "Tab", "Space",
		"F1", "F12", "ArrowRight", "ArrowLeft", "ArrowDown", "ArrowUp",
		"Home", "End",
		"ControlLeft", "ShiftLeft", "AltLeft", "MetaLeft",
	}
	for _, code := range common {
		if _, err := libghostty.ParseKey(w3cKeyName(code)); err != nil {
			t.Errorf("%q does not reach ghostty: %v", code, err)
		}
	}
}
